# -*- coding: utf8 -*-
#
# Copyright (C) 2014 NDP Systèmes (<http://www.ndp-systemes.fr>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

{
    'name': 'Group Purchase Lines By Period',
    'version': '0.1',
    'author': 'NDP Systèmes',
    'maintainer': 'NDP Systèmes',
    'category': 'Purchase',
    'depends': ['base','purchase'],
    'description': """
Group Purchase Lines By Period
==============================
With this module installed, purchase order lines generated by procurements are grouped into several purchase orders
based on their date, instead of all being added to the first draft PO found for the same supplier and same address.

For each supplier, a grouping time frame is selected. Time frames can be expressed among:
- Day
- Week
- Fortnight
- Month

Depending on this time frame, the purchase order lines are grouped into one purchase order per time frame.
""",
    'website': 'http://www.ndp-systemes.fr',
    'data': [
        'purchase_group_by_period_view.xml',
        'purchase_group_by_period_data.xml'
    ],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'license': 'AGPL-3',
    'application': False,
}
